{"name": "test_get_user_with_invalid_value_002", "status": "passed", "description": "create_user_with_invalid_values", "start": 1662025921689, "stop": 1662025924946, "uuid": "3c930164-5f3a-47fc-af86-b12aaaac1435", "historyId": "81e1b0e5a9a63fc8c5dca972ff07e887", "testCaseId": "bbc5923e2dc6466fcae592ea08eff47d", "fullName": "Test_case.Test_Get_User_API#test_get_user_with_invalid_value_002", "labels": [{"name": "severity", "value": "Normal"}, {"name": "parentSuite", "value": "Test_case"}, {"name": "suite", "value": "Test_Get_User_API"}, {"name": "host", "value": "DESKTOP-KBHEFTS"}, {"name": "thread", "value": "22096-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_case.Test_Get_User_API"}]}