{"name": "test_get_user_with_invalid_value_002", "status": "passed", "description": "create_user_with_invalid_values", "start": 1662026054936, "stop": 1662026056097, "uuid": "d1bacd3d-dc75-4727-b694-30d802764a31", "historyId": "81e1b0e5a9a63fc8c5dca972ff07e887", "testCaseId": "bbc5923e2dc6466fcae592ea08eff47d", "fullName": "Test_case.Test_Get_User_API#test_get_user_with_invalid_value_002", "labels": [{"name": "severity", "value": "Normal"}, {"name": "parentSuite", "value": "Test_case"}, {"name": "suite", "value": "Test_Get_User_API"}, {"name": "host", "value": "DESKTOP-KBHEFTS"}, {"name": "thread", "value": "17708-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_case.Test_Get_User_API"}]}